### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by bdenney** [learn-co-curriculum/python-p3-inheritance-lab#1]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/195253?module_item_id=439035

### Concern

Needed to google a good bit for “Object Inheritance Lab, Part One”. Especially invoking super constructor (which seems like was the goal) and using random. (Seeing that super actually immediately follows this lesson so maybe super wasn’t the goal).

**Comment by professor-ben** [comment]
Hi Brandon,

My intention here was to give the students a bit of a challenge and show the need for `super` before its introduction. I think that based on feedback from you and a couple of other instructors, I need to provide more scaffolding in the instructions and the lab file. I'll push up a change soon.

-Ben

**Comment by professor-ben** [comment]
Upon review, I think that approaching this without `super` doesn't add much value and requires the inclusion of class attributes and methods- not covered until later in the new curriculum. I've moved this lab to follow the lesson on `super` and immediately precede python-p3-inheritance-lab-pt-2.

-Ben
