### ISSUE TITLE
Instructions out of Sync with Lab / Question about Intention

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p3-inheritance-lab#2]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/195253?module_item_id=439035

### Concern

**1.** We tell students to modify the `Teacher` and `Student` classes such that they inherit from the `User` class, but they're already set up to inherit from the `User` class when we open the lab.

**2.** We tell students that the `Student` class will pass a few tests because it's inheriting from the `User` class, which already has an `__init__` method. However, we need to initialize an instance of our `Student` class with something more than what is controlled by the `User` class - a knowledge attribute that starts out with the value of an empty list. Doesn't this mean we'll have to rewrite our `__init__` method for our `Student` class? In which case we will also have to tell this `Student` `__init__` method to initialize the `first_name` and `last_name` attributes? Is our goal to get students to realize that they have to redeclare this whole method, including the `first_name` and `last_name` attributes? If so, our intention isn't that clear in the instructions (which may be desired, depending on the approach we want to take). Or am I missing something?

**Comment by Matt-Eva** [comment]
Just realized that issue number 2 can be solved by the use of the `super` keyword, which we don't discuss until the following section. I raised an issue pertaining to this on that reading as well with some further comments.

**Comment by professor-ben** [comment]
A lot of feedback came in on this one- I pushed a number of changes that should address your concerns here. These will be reflected in the release for the next build (though you can also check them on GitHub anytime!)
