### ISSUE TITLE
testing issue

### ISSUE THREAD

**Issue by DavidWolff218** [learn-co-curriculum/python-p3-inheritance-lab#3]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/195253?module_item_id=439035

### Concern

The lab talks about working on the Teacher class and getting tests to pass for that, but the testing seems to be working on the student class to start with. It is making it a little awkward to try and understand what is and isn't working when running pytest -x

**Comment by sheenasany** [comment]
I second this. I came across this today and was incredibly confused as to why my teacher class wasn't passing the requirements as it's 2. on the set of instructions in Canvas. Until I looked closely at the test where it was telling me to initialize in Student class. I've included an image to iterate this. 

![image](https://user-images.githubusercontent.com/105241920/213831906-01c1151a-0c47-400a-ab34-66d6cfa5c14b.png)

**Comment by professor-ben** [comment]
I just added in a pytest lesson to provide students with some more tools to organize the order their tests run in, so I'll update the instructions here so as to remind them here. This is just an alphabetical issue- sorry for not catching it in dev!

**Comment by professor-ben** [comment]
Fixed with most recent commit.
